language: node_js
node_js:
  - "stable"
services: mongodb
install:
  - npm ci
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm test
after_success:
  - npm run coverage
