language: node_js
node_js:
  - "12"
install:
  - npm i
cache:
  directories:
    - node_modules/
services:
  - mongodb
before_script:
  - sleep 15
  - mongo gms_server --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm test
after_success:
  - npm run coverage
